id: P010363
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG4334
  title: དཔལ་སྤུངས་དཔེ་རྙིང་གསར་བསྐྲུན་ལས་དཀྱིལ་ཆོག་ཕྱོགས་བསྒྲིགས། ༼དང་པོ།༽
  author: ''
  volumes:
    22847c8264404923adf06d61101e88a3:
      image_group_id: I1KG4342
      title: ''
      volume_number: 1
      total_pages: 368
      base_file: v001.txt
    b1e881c3d1f5469599b604636f327c36:
      image_group_id: I1KG4343
      title: ''
      volume_number: 2
      total_pages: 428
      base_file: v002.txt
    cf8342719f054a3685f3456f27896fb6:
      image_group_id: I1KG4344
      title: ''
      volume_number: 3
      total_pages: 210
      base_file: v003.txt
    a8587cbed05248579e395df52c89797e:
      image_group_id: I1KG4345
      title: ''
      volume_number: 4
      total_pages: 1038
      base_file: v004.txt
    2cddff57eef941c285364c8b8c485ada:
      image_group_id: I1KG4346
      title: ''
      volume_number: 5
      total_pages: 192
      base_file: v005.txt
    7e1564158bb8475eb90f2f2fcc788f1e:
      image_group_id: I1KG4347
      title: ''
      volume_number: 6
      total_pages: 210
      base_file: v006.txt
    8a0115ce702e4b64a04f750891838cc9:
      image_group_id: I1KG4348
      title: ''
      volume_number: 7
      total_pages: 370
      base_file: v007.txt
    d1796174b1a044288826c1ee44386900:
      image_group_id: I1KG4349
      title: ''
      volume_number: 8
      total_pages: 284
      base_file: v008.txt
    98c533931459410b9d7927982c69b53e:
      image_group_id: I1KG4350
      title: ''
      volume_number: 9
      total_pages: 532
      base_file: v009.txt
    605ad3bf59f547bab5dcb7bd9ffbeaa0:
      image_group_id: I1KG4351
      title: ''
      volume_number: 10
      total_pages: 490
      base_file: v010.txt
    bfe28d5a3f594a0a8b1e0a126c4f04f3:
      image_group_id: I1KG4352
      title: ''
      volume_number: 11
      total_pages: 302
      base_file: v011.txt
    c7947cc3afb64088823d5e1b21cf4f67:
      image_group_id: I1KG4353
      title: ''
      volume_number: 12
      total_pages: 400
      base_file: v012.txt
    e86874409ad44a26b85ad8a9b3390a46:
      image_group_id: I1KG4354
      title: ''
      volume_number: 13
      total_pages: 698
      base_file: v013.txt
    3c78004b48a048d28f4cc3fcae6fd820:
      image_group_id: I1KG4355
      title: ''
      volume_number: 14
      total_pages: 226
      base_file: v014.txt
