id: I3DE6B40E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T06:07:01+00:00'
last_modified: '2022-06-08T13:02:28.911800+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4334
  title: དཔལ་སྤུངས་དཔེ་རྙིང་གསར་བསྐྲུན་ལས་དཀྱིལ་ཆོག་ཕྱོགས་བསྒྲིགས། ༼དང་པོ།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    E3B1:
      image_group_id: I1KG4342
      title: ''
      total_pages: 368
      order: 1
      base_file: E3B1.txt
    '0404':
      image_group_id: I1KG4343
      title: ''
      total_pages: 428
      order: 2
      base_file: 0404.txt
    7F0F:
      image_group_id: I1KG4344
      title: ''
      total_pages: 210
      order: 3
      base_file: 7F0F.txt
    C942:
      image_group_id: I1KG4345
      title: ''
      total_pages: 1038
      order: 4
      base_file: C942.txt
    4D48:
      image_group_id: I1KG4346
      title: ''
      total_pages: 192
      order: 5
      base_file: 4D48.txt
    '7497':
      image_group_id: I1KG4347
      title: ''
      total_pages: 210
      order: 6
      base_file: 7497.txt
    42B0:
      image_group_id: I1KG4348
      title: ''
      total_pages: 370
      order: 7
      base_file: 42B0.txt
    CCF0:
      image_group_id: I1KG4349
      title: ''
      total_pages: 284
      order: 8
      base_file: CCF0.txt
    A2F9:
      image_group_id: I1KG4350
      title: ''
      total_pages: 532
      order: 9
      base_file: A2F9.txt
    7C68:
      image_group_id: I1KG4351
      title: ''
      total_pages: 490
      order: 10
      base_file: 7C68.txt
    '8884':
      image_group_id: I1KG4352
      title: ''
      total_pages: 302
      order: 11
      base_file: 8884.txt
    C7B7:
      image_group_id: I1KG4353
      title: ''
      total_pages: 400
      order: 12
      base_file: C7B7.txt
    '0264':
      image_group_id: I1KG4354
      title: ''
      total_pages: 698
      order: 13
      base_file: 0264.txt
    F2FB:
      image_group_id: I1KG4355
      title: ''
      total_pages: 226
      order: 14
      base_file: F2FB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
